<?php
// $Id: wf_field.install$

/**
 * @file
 * Install/Update/Uninstall functions for field_example module
 */

/**
 * Implements hook_field_schema().
 *
 * @see hook_field_schema()
 * @link schemaapi Schema API @endlink
 */
function wf_field_field_schema($field) {
  $columns = array(
    'wf_state' => array('type' => 'int', 'not null' => FALSE),
  );
  $indexes = array(
    'wf_state' => array('wf_state'),
  );
  return array(
    'columns' => $columns,
    'indexes' => $indexes,
  );
}
